Repository jenkinsci/oss-symbols-api-plugin, pull requests merged in 2024-09, with the labels that each got.

#11 Update broken badge
  README.md
Labels: documentation

#12 More logos
  src/main/resources/images/symbols/artifacthub-icon-color.svg
  src/main/resources/images/symbols/cert-manager-icon-solid.svg
  src/main/resources/images/symbols/chaosmesh-icon-solid.svg
  src/main/resources/images/symbols/cni-icon-color.svg
  src/main/resources/images/symbols/cni-icon-solid.svg
  src/main/resources/images/symbols/contour-icon-color.svg
  src/main/resources/images/symbols/contour-icon-solid.svg
  src/main/resources/images/symbols/coredns-icon-color.svg
  src/main/resources/images/symbols/coredns-icon-solid.svg
  src/main/resources/images/symbols/cortex-icon-color.svg
  src/main/resources/images/symbols/cortex-icon-solid.svg
  src/main/resources/images/symbols/crossplane-icon-color.svg
  src/main/resources/images/symbols/crossplane-icon-solid.svg
  src/main/resources/images/symbols/cubefs-icon-color.svg
  src/main/resources/images/symbols/cubefs-icon-solid.svg
  src/main/resources/images/symbols/dapr-icon-color.svg
  src/main/resources/images/symbols/dapr-icon-solid.svg
  src/main/resources/images/symbols/dragonfly-icon-color.svg
  src/main/resources/images/symbols/dragonfly-icon-icon.svg
  src/main/resources/images/symbols/emissary-ingress-icon-color.svg
  src/main/resources/images/symbols/emissary-ingress-icon-icon.svg
  src/main/resources/images/symbols/flagger-icon-color.svg
  src/main/resources/images/symbols/fluentbit-icon-color.svg
  src/main/resources/images/symbols/fluentbit-icon-solid.svg
  src/main/resources/images/symbols/fluentd-icon-solid.svg
  src/main/resources/images/symbols/in-toto-icon-color.svg
  src/main/resources/images/symbols/in-toto-icon-solid.svg
  src/main/resources/images/symbols/karmada-icon-color.svg
  src/main/resources/images/symbols/karmada-icon-solid.svg
  src/main/resources/images/symbols/keptn-icon-solid.svg
  src/main/resources/images/symbols/keycloak-icon-color.svg
  src/main/resources/images/symbols/keycloak-icon-solid.svg
  src/main/resources/images/symbols/mariadb-icon-solid.svg
  src/main/resources/images/symbols/mariadb-logo-color.svg
  src/main/resources/images/symbols/postgresql-icon-color.svg
  src/main/resources/images/symbols/postgresql-icon-solid.svg
  src/main/resources/images/symbols/tikv-icon-solid.svg
Labels: enhancement

#18 Add OWASP icon
  src/main/resources/images/symbols/owasp-icon-color.svg
  src/main/resources/images/symbols/owasp-icon-solid.svg
Labels: enhancement

#21 Add OKD logo
  src/main/resources/images/symbols/okd-icon-color.svg
  src/main/resources/images/symbols/okd-icon-solid.svg
Labels: chore

#22 Add OpenID logo
  src/main/resources/images/symbols/openid-icon-color.svg
  src/main/resources/images/symbols/openid-icon-solid.svg
Labels: chore

#23 Testcontainers logo
  .vscode/settings.json
  src/main/resources/images/symbols/testcontainers-icon-color.svg
  src/main/resources/images/symbols/testcontainers-icon-solid.svg
Labels: chore

#24 Add wiremock logo
  src/main/resources/images/symbols/wiremock-icon-color.svg
  src/main/resources/images/symbols/wiremock-icon-solid.svg
Labels: enhancement

#26 Add OpenRewrite logo
  README.md
  src/main/resources/images/symbols/openrewrite-icon-color.svg
  src/main/resources/images/symbols/openrewrite-icon-solid.svg
Labels: chore

#27 Add renovate logo
  .vscode/settings.json
  src/main/resources/images/symbols/renovate-icon-color.svg
  src/main/resources/images/symbols/renovate-icon-solid.svg
Labels: enhancement

#29 Add OCI logo
  README.md
  src/main/resources/images/symbols/oci-icon-color.svg
  src/main/resources/images/symbols/oci-icon-solid.svg
Labels: enhancement

#31 SonarQube logo
  src/main/resources/images/symbols/sonarqube-icon-color.svg
  src/main/resources/images/symbols/sonarqube-icon-solid.svg
Labels: chore

#32 Python icon
  src/main/resources/images/symbols/python-icon-color.svg
  src/main/resources/images/symbols/python-icon-solid.svg
Labels: enhancement

#38 Pulumi logo
  README.md
  src/main/resources/images/symbols/pulumi-icon-color.svg
  src/main/resources/images/symbols/pulumi-icon-solid.svg
Labels: chore

#39 OpenTofu logo
  src/main/resources/images/symbols/opentofu-icon-color.svg
  src/main/resources/images/symbols/opentofu-icon-solid.svg
Labels: chore

#40 Add Ansible logo
  src/main/resources/images/symbols/ansible-icon-color.svg
  src/main/resources/images/symbols/ansible-icon-solid.svg
Labels: enhancement

#41 Add Atlassian icons
  src/main/resources/images/symbols/bitbucket-icon-color.svg
  src/main/resources/images/symbols/bitbucket-icon-solid.svg
  src/main/resources/images/symbols/confluence-icon-color.svg
  src/main/resources/images/symbols/confluence-icon-solid.svg
  src/main/resources/images/symbols/jira-icon-color.svg
  src/main/resources/images/symbols/jira-icon-solid.svg
  src/main/resources/images/symbols/jira-service-management-icon-color.svg
  src/main/resources/images/symbols/jira-service-management-icon-solid.svg
Labels: enhancement

#42 Add Artifactory and XRay logo
  src/main/resources/images/symbols/jfrog-artifactory-icon-color.svg
  src/main/resources/images/symbols/jfrog-artifactory-icon-solid.svg
  src/main/resources/images/symbols/jfrog-xray-icon-color-solid.svg
  src/main/resources/images/symbols/jfrog-xray-icon-color.svg
Labels: enhancement

#44 Resize / center OWASP icon
  src/main/resources/images/symbols/owasp-icon-color.svg
  src/main/resources/images/symbols/owasp-icon-solid.svg
Labels: bug

#45 Fix logo name
  src/main/resources/images/symbols/jfrog-xray-icon-solid.svg
Labels: chore

#46 Openstack logo
  src/main/resources/images/symbols/openstack-icon-color.svg
  src/main/resources/images/symbols/openstack-icon-solid.svg
Labels: enhancement

#47 Add java logo
  src/main/resources/images/symbols/java-icon-color.svg
  src/main/resources/images/symbols/java-icon-solid.svg
Labels: chore

#48 Add Jenkins logo
  src/main/resources/images/symbols/jenkins-icon-solid.svg
Labels: enhancement

#50 LGTM stack
  src/main/resources/images/symbols/grafana-icon-color.svg
  src/main/resources/images/symbols/grafana-icon-solid.svg
  src/main/resources/images/symbols/loki-icon-color.svg
  src/main/resources/images/symbols/loki-icon-solid.svg
  src/main/resources/images/symbols/mimir-icon-color.svg
  src/main/resources/images/symbols/mimir-icon-solid.svg
  src/main/resources/images/symbols/tempo-icon-color.svg
  src/main/resources/images/symbols/tempo-icon-solid.svg
Labels: enhancement

#51 Apache Maven
  src/main/resources/images/symbols/apache-maven-icon-color.svg
  src/main/resources/images/symbols/apache-maven-icon-solid.svg
  src/main/resources/images/symbols/apache-maven-rectangle-color.svg
  src/main/resources/images/symbols/apache-maven-rectangle-solid.svg
Labels: enhancement
