Repository jenkinsci/oss-symbols-api-plugin, pull requests merged in 2024-08, with the labels that each got.

#1 Add more logos
  src/main/resources/images/symbols/artifacthub-icon.svg
  src/main/resources/images/symbols/buildpacks-icon-black.svg
  src/main/resources/images/symbols/falco-icon.svg
  src/main/resources/images/symbols/flagger-icon.svg
  src/main/resources/images/symbols/fluentd-icon.svg
  src/main/resources/images/symbols/grpc-icon.svg
  src/main/resources/images/symbols/keda-icon.svg
  src/main/resources/images/symbols/linkerd-icon.svg
  src/main/resources/images/symbols/spiffe-icon.svg
  src/main/resources/images/symbols/spire-icon.svg
  src/main/resources/images/symbols/tuf-icon.svg
  src/main/resources/images/symbols/vitess-icon-black.svg
Labels: enhancement

#3 Fix CD config
  pom.xml
Labels: developer

#4 Fix badge
  README.md
Labels: documentation

#5 Fix some svg color icon
  README.md
  docs/folder_icon.png
  docs/header.png
  src/main/resources/images/symbols/argo-icon-color.svg
  src/main/resources/images/symbols/backstage-icon-color.svg
  src/main/resources/images/symbols/cdevents_icon-color.svg
  src/main/resources/images/symbols/cdf-icon-color.svg
  src/main/resources/images/symbols/cert-manager-icon-color.svg
  src/main/resources/images/symbols/chaosmesh-icon-color.svg
  src/main/resources/images/symbols/cilium-icon-color.svg
  src/main/resources/images/symbols/cilium_icon-color.svg
  src/main/resources/images/symbols/cloudevents-icon-color.svg
  src/main/resources/images/symbols/containerd-icon-color.svg
  src/main/resources/images/symbols/coredns-icon-color.svg
  src/main/resources/images/symbols/crio-icon-color.svg
  src/main/resources/images/symbols/envoy-icon-color.svg
  src/main/resources/images/symbols/etcd-icon-color.svg
  src/main/resources/images/symbols/falco-icon-color.svg
  src/main/resources/images/symbols/flagger-icon-color.svg
  src/main/resources/images/symbols/fluentd-icon-color.svg
  src/main/resources/images/symbols/fluentd-icon-solid.svg
  src/main/resources/images/symbols/flux-icon-color.svg
  src/main/resources/images/symbols/grpc-icon-color.svg
  src/main/resources/images/symbols/harbor-icon-color.svg
  src/main/resources/images/symbols/helm-icon-color.svg
  src/main/resources/images/symbols/istio-icon-color.svg
  src/main/resources/images/symbols/jaeger-icon-color.svg
  src/main/resources/images/symbols/jenkinsx-icon-color.svg
  src/main/resources/images/symbols/jenkinsx-icon-solid.svg
  src/main/resources/images/symbols/k3s-icon-color.svg
  src/main/resources/images/symbols/keda-icon-color.svg
  src/main/resources/images/symbols/keptn-icon-color.svg
  src/main/resources/images/symbols/kubernetes-icon-color.svg
  src/main/resources/images/symbols/linkerd-icon-color.svg
  src/main/resources/images/symbols/longhorn-icon-color.svg
  src/main/resources/images/symbols/notary-project-icon-color.svg
  src/main/resources/images/symbols/opa-icon-color.svg
  src/main/resources/images/symbols/opentelemetry-icon-color.svg
  src/main/resources/images/symbols/operatorframework-icon-color.svg
  src/main/resources/images/symbols/rook-icon-color.svg
  src/main/resources/images/symbols/screwdriver-icon-color.svg
  src/main/resources/images/symbols/spiffe-icon-color.svg
  src/main/resources/images/symbols/spinnaker-icon-color.svg
  src/main/resources/images/symbols/spire-icon-color.svg
  src/main/resources/images/symbols/tekton-icon-color.svg
  src/main/resources/images/symbols/tikv-icon-color.svg
  src/main/resources/images/symbols/tuf-icon-color.svg
  src/main/resources/images/symbols/vitess-icon-color.svg
Labels: bug

#6 Fix typo in icon filename
  src/main/resources/images/symbols/cdevents-icon-color.svg
Labels: chore

#8 Update Jenkins Security Scan action
  .github/workflows/jenkins-security-scan.yml
Labels: chore

#7 Remove dependency management
  pom.xml
Labels: dependencies

#9 Add linux/homebrew logos
  src/main/resources/images/symbols/homebrew-icon-color.svg
  src/main/resources/images/symbols/linuxbrew-icon-color.svg
Labels: chore

#10 Add sigstore project symbols
  README.md
  src/main/resources/images/symbols/buildpacks-icon-solid.svg
  src/main/resources/images/symbols/cloudevents-icon-color.svg
  src/main/resources/images/symbols/cosign-icon-color.svg
  src/main/resources/images/symbols/cosign-icon-solid.svg
  src/main/resources/images/symbols/fulcio-icon-color.svg
  src/main/resources/images/symbols/fulcio-icon-solid.svg
  src/main/resources/images/symbols/gitsign-icon-color.svg
  src/main/resources/images/symbols/gitsign-icon-solid.svg
  src/main/resources/images/symbols/policycontroller-icon-color.svg
  src/main/resources/images/symbols/policycontroller-icon-solid.svg
  src/main/resources/images/symbols/rekor-icon-color.svg
  src/main/resources/images/symbols/rekor-icon-solid.svg
  src/main/resources/images/symbols/sigstore-icon-color.svg
  src/main/resources/images/symbols/sigstore-icon-solid.svg
  src/main/resources/images/symbols/vitess-icon-solid.svg
Labels: chore
