Repository jenkinsci/oss-symbols-api-plugin, pull requests merged in 2024-11, with the labels that each got.

#57 Add new SonarQube logos
  src/main/resources/images/symbols/sonarqube-cloud-icon-color.svg
  src/main/resources/images/symbols/sonarqube-cloud-icon-solid.svg
  src/main/resources/images/symbols/sonarqube-ide-icon-color.svg
  src/main/resources/images/symbols/sonarqube-ide-icon-solid.svg
  src/main/resources/images/symbols/sonarqube-server-icon-color.svg
  src/main/resources/images/symbols/sonarqube-server-icon-solid.svg
Labels: enhancement

#58 Add vite and spring logos
  src/main/resources/images/symbols/spring-icon-color.svg
  src/main/resources/images/symbols/spring-icon-solid.svg
  src/main/resources/images/symbols/vite-icon-color.svg
  src/main/resources/images/symbols/vite-icon-solid.svg
Labels: enhancement

#59 Add angular logo
  src/main/resources/images/symbols/angular-icon-color.svg
  src/main/resources/images/symbols/angular-icon-solid.svg
Labels: dependencies

#62 Add hypervisors (AWS, Azure and GCP)
  src/main/resources/images/symbols/aws-icon-color.svg
  src/main/resources/images/symbols/aws-icon-solid.svg
  src/main/resources/images/symbols/azure-icon-color.svg
  src/main/resources/images/symbols/azure-icon-solid.svg
  src/main/resources/images/symbols/gcp-icon-color.svg
  src/main/resources/images/symbols/gcp-icon-solid.svg
Labels: chore

#63 Add gradle icon
  README.md
  src/main/resources/images/symbols/gradle-icon-solid.svg
  src/main/resources/images/symbols/gradle-icon-solor.svg
Labels: chore

#64 Add go icon
  src/main/resources/images/symbols/go-icon-color.svg
  src/main/resources/images/symbols/go-icon-solid.svg
Labels: chore

#65 Add vscode icon
  src/main/resources/images/symbols/vscode-icon-color.svg
  src/main/resources/images/symbols/vscode-icon-solid.svg
Labels: chore

#67 Add vue js
  src/main/resources/images/symbols/vuejs-icon-color.svg
  src/main/resources/images/symbols/vuejs-icon-solid.svg
Labels: chore

#68 Add ubuntu
  src/main/resources/images/symbols/ubuntu-icon-color.svg
  src/main/resources/images/symbols/ubuntu-icon-solid.svg
Labels: chore

#69 Add bash and ohmyzsh
  src/main/resources/images/symbols/bash-icon-color.svg
  src/main/resources/images/symbols/bash-icon-solid.svg
  src/main/resources/images/symbols/ohmyzsh-icon-color.svg
  src/main/resources/images/symbols/ohmyzsh-icon-solid.svg
Labels: chore

#70 Add several format (YAML, XML and JSON)
  src/main/resources/images/symbols/json-icon-color.svg
  src/main/resources/images/symbols/json-icon-solid.svg
  src/main/resources/images/symbols/xml-icon-color.svg
  src/main/resources/images/symbols/xml-icon-solid.svg
  src/main/resources/images/symbols/yaml-icon-color.svg
  src/main/resources/images/symbols/yaml-icon-solid.svg
Labels: chore

#71 Add podman icon
  src/main/resources/images/symbols/podman-icon-color.svg
  src/main/resources/images/symbols/podman-icon-solid.svg
Labels: chore

#72 Add intellij icon
  src/main/resources/images/symbols/intellij-icon-color.svg
  src/main/resources/images/symbols/intellij-icon-solid.svg
Labels: chore

#73 Add eclipse icon
  src/main/resources/images/symbols/eclipse-icon-color.svg
  src/main/resources/images/symbols/eclipse-icon-solid.svg
Labels: chore

#74 Add debian
  src/main/resources/images/symbols/debian-icon-color.svg
  src/main/resources/images/symbols/debian-icon-solid.svg
Labels: chore

#75 Add vim logo
  src/main/resources/images/symbols/vim-icon-color.svg
  src/main/resources/images/symbols/vim-icon-solid.svg
Labels: chore

#76 Add visualstudio icon
  src/main/resources/images/symbols/visualstudio-icon-color.svg
  src/main/resources/images/symbols/visualstudio-icon-solid.svg
Labels: chore

#77 Add tomcat logo
  src/main/resources/images/symbols/tomcat-icon-color.svg
  src/main/resources/images/symbols/tomcat-icon-solid.svg
Labels: chore

#78 Update doc and add total of tools badge
  README.md
  pom.xml
Labels: documentation

#79 Add icons for mobile dev
  src/main/resources/images/symbols/android-icon-color.svg
  src/main/resources/images/symbols/android-icon-solid.svg
  src/main/resources/images/symbols/android-studio-icon-color.svg
  src/main/resources/images/symbols/android-studio-icon-solid.svg
  src/main/resources/images/symbols/apple-icon-color.svg
  src/main/resources/images/symbols/apple-icon-solid.svg
Labels: chore

#80 Add F# and C# and fix class on .NET logo
  src/main/resources/images/symbols/csharp-icon-color.svg
  src/main/resources/images/symbols/csharp-icon-solid.svg
  src/main/resources/images/symbols/dotnet-logo-solid.svg
  src/main/resources/images/symbols/fsharp-icon-color.svg
  src/main/resources/images/symbols/fsharp-icon-solid.svg
Labels: chore

#81 Add more ASF logos
  src/main/resources/images/symbols/apache-airflow-color.svg
  src/main/resources/images/symbols/apache-airflow-solid.svg
  src/main/resources/images/symbols/apache-icon-color.svg
  src/main/resources/images/symbols/apache-icon-solid.svg
  src/main/resources/images/symbols/apache-kafka-icon-color.svg
  src/main/resources/images/symbols/apache-kafka-icon-solid.svg
  src/main/resources/images/symbols/apache-spark-icon-color.svg
  src/main/resources/images/symbols/apache-spark-icon-solid.svg
Labels: chore

#83 Add HTML5 and CSS3 logos
  src/main/resources/images/symbols/babel-icon-color.svg
  src/main/resources/images/symbols/babel-icon-solid.svg
  src/main/resources/images/symbols/css3-icon-color.svg
  src/main/resources/images/symbols/css3-icon-solid.svg
  src/main/resources/images/symbols/html5-icon-color.svg
  src/main/resources/images/symbols/html5-icon-solid.svg
  src/main/resources/images/symbols/sass-icon-color.svg
  src/main/resources/images/symbols/sass-icon-solid.svg
Labels: chore

#85 Add drupal logo
  src/main/resources/images/symbols/drupal-icon-color.svg
  src/main/resources/images/symbols/drupal-icon-solid.svg
Labels: chore

#88 Add grunt logo
  src/main/resources/images/symbols/grunt-icon-color.svg
  src/main/resources/images/symbols/grunt-icon-solid.svg
Labels: chore

#87 Add kotlin and groovy logo
  src/main/resources/images/symbols/groovy-icon-color.svg
  src/main/resources/images/symbols/groovy-icon-solid.svg
  src/main/resources/images/symbols/kotlin-icon-color.svg
  src/main/resources/images/symbols/kotlin-icon-solid.svg
Labels: chore

#89 Add ORAS
  src/main/resources/images/symbols/oras-icon-color.svg
  src/main/resources/images/symbols/oras-icon-solid.svg
Labels: chore

#90 Add hashicorp tools
  README.md
  src/main/resources/images/symbols/boundary-icon-color.svg
  src/main/resources/images/symbols/boundary-icon-solid.svg
  src/main/resources/images/symbols/consul-icon-color.svg
  src/main/resources/images/symbols/consul-icon-solid.svg
  src/main/resources/images/symbols/hashicorp-icon-color.svg
  src/main/resources/images/symbols/hashicorp-icon-solid.svg
  src/main/resources/images/symbols/nomad-icon-color.svg
  src/main/resources/images/symbols/nomad-icon-solid.svg
  src/main/resources/images/symbols/packer-icon-color.svg
  src/main/resources/images/symbols/packer-icon-solid.svg
  src/main/resources/images/symbols/terraform-icon-color.svg
  src/main/resources/images/symbols/terraform-icon-solid.svg
  src/main/resources/images/symbols/vagrant-icon-color.svg
  src/main/resources/images/symbols/vagrant-icon-solid.svg
  src/main/resources/images/symbols/vault-icon-color.svg
  src/main/resources/images/symbols/vault-icon-solid.svg
  src/main/resources/images/symbols/waypoint-icon-color.svg
  src/main/resources/images/symbols/waypoint-icon-solid.svg
Labels: enhancement

#91 Add next.js logo
  src/main/resources/images/symbols/nextjs-icon-color.svg
  src/main/resources/images/symbols/nextjs-icon-solid.svg
Labels: chore

#92 Add mongodb
  src/main/resources/images/symbols/mongodb-icon-color.svg
  src/main/resources/images/symbols/mongodb-icon-solid.svg
Labels: chore

#93 Add microsoft sqlserver
  src/main/resources/images/symbols/microsoftsqlserver-icon-color.svg
  src/main/resources/images/symbols/microsoftsqlserver-icon-solid.svg
Labels: chore

#94 Add fastapi logo
  src/main/resources/images/symbols/fastapi-icon-color.svg
  src/main/resources/images/symbols/fastapi-icon-solid.svg
Labels: chore

#95 Add npm and nodejs
  src/main/resources/images/symbols/nodejs-icon-color.svg
  src/main/resources/images/symbols/nodejs-icon-solid.svg
  src/main/resources/images/symbols/npm-icon-color.svg
  src/main/resources/images/symbols/npm-icon-solid.svg
Labels: chore

#96 Add nuget logo
  src/main/resources/images/symbols/nuget-icon-color.svg
  src/main/resources/images/symbols/nuget-icon-solid.svg
Labels: chore

#97 Add vpshere icon
  src/main/resources/images/symbols/vpshere-icon-color.svg
  src/main/resources/images/symbols/vpshere-icon-solid.svg
Labels: chore

#98 Add linux mint
  src/main/resources/images/symbols/linuxmint-icon-color.svg
  src/main/resources/images/symbols/linuxmint-icon-solid.svg
Labels: chore

#100 Add cypress, selenium and playwright
  src/main/resources/images/symbols/cypress-icon-color.svg
  src/main/resources/images/symbols/cypress-icon-solid.svg
  src/main/resources/images/symbols/playwright-icon-color.svg
  src/main/resources/images/symbols/playwright-icon-solid.svg
  src/main/resources/images/symbols/selenium-icon-color.svg
  src/main/resources/images/symbols/selenium-icon-solid.svg
Labels: chore

#102 Add redis logo
  src/main/resources/images/symbols/redis-icon-color.svg
  src/main/resources/images/symbols/redis-icon-solid.svg
Labels: chore

#101 Add wordpress icon
  src/main/resources/images/symbols/wordpress-icon-color.svg
  src/main/resources/images/symbols/wordpress-icon-solid.svg
Labels: chore

#103 Fix icon count badge
  README.md
Labels: documentation

#104 Add pytest
  src/main/resources/images/symbols/pytest-icon-color.svg
  src/main/resources/images/symbols/pytest-icon-solid.svg
Labels: chore

#106 Add xcode logo
  src/main/resources/images/symbols/xcode-icon-color.svg
  src/main/resources/images/symbols/xcode-icon-solid.svg
Labels: chore

#107 Add zsh logo
  src/main/resources/images/symbols/zsh-icon-color.svg
  src/main/resources/images/symbols/zsh-icon-solid.svg
Labels: chore

#110 Add unix icon
  src/main/resources/images/symbols/unix-icon-color.svg
  src/main/resources/images/symbols/unix-icon-solid.svg
Labels: chore

#111 add eslint
  src/main/resources/images/symbols/eslint-icon-color.svg
  src/main/resources/images/symbols/eslint-icon-solid.svg
Labels: chore

#112 Add jest logo
  src/main/resources/images/symbols/jest-icon-color.svg
  src/main/resources/images/symbols/jest-icon-solid.svg
Labels: chore

#113 Add codecov
  src/main/resources/images/symbols/codecov-icon-color.svg
  src/main/resources/images/symbols/codecov-icon-solid.svg
Labels: chore

#115 Add rancher logos
  README.md
  src/main/resources/images/symbols/fleet-icon-color.svg
  src/main/resources/images/symbols/fleet-icon-solid.svg
  src/main/resources/images/symbols/harvester-icon-color.svg
  src/main/resources/images/symbols/harvester-icon-solid.svg
  src/main/resources/images/symbols/k3os-icon-color.svg
  src/main/resources/images/symbols/k3os-icon-solid.svg
  src/main/resources/images/symbols/k3s-icon-color.svg
  src/main/resources/images/symbols/k3s-icon-solid.svg
  src/main/resources/images/symbols/kubewarden-icon-color.svg
  src/main/resources/images/symbols/kubewarden-icon-solid.svg
  src/main/resources/images/symbols/longhorn-icon-color.svg
  src/main/resources/images/symbols/longhorn-icon-solid.svg
  src/main/resources/images/symbols/rancher-desktop-color.svg
  src/main/resources/images/symbols/rancher-desktop-solid.svg
  src/main/resources/images/symbols/rancher-logo-color.svg
  src/main/resources/images/symbols/rancher-logo-solid.svg
  src/main/resources/images/symbols/rio-icon-color.svg
  src/main/resources/images/symbols/rio-icon-solid.svg
  src/main/resources/images/symbols/rke-icon-color.svg
  src/main/resources/images/symbols/rke-icon-solid.svg
Labels: chore

#117 Add git symbol
  src/main/resources/images/symbols/git-icon-color.svg
  src/main/resources/images/symbols/git-icon-solid.svg
Labels: chore

#120 Add browser icons
  src/main/resources/images/symbols/chrome-icon-color.svg
  src/main/resources/images/symbols/chrome-icon-solid.svg
  src/main/resources/images/symbols/firefox-icon-color.svg
  src/main/resources/images/symbols/firefox-icon-solid.svg
  src/main/resources/images/symbols/opera-icon-color.svg
  src/main/resources/images/symbols/opera-icon-solid.svg
  src/main/resources/images/symbols/safari-icon-color.svg
  src/main/resources/images/symbols/safari-icon-solid.svg
Labels: chore

#119 add minio logo
  src/main/resources/images/symbols/minio-icon-color.svg
  src/main/resources/images/symbols/minio-icon-solid.svg
Labels: chore

#121 Sonatype products logo
  README.md
  src/main/resources/images/symbols/sonatype-firewall-icon-color.svg
  src/main/resources/images/symbols/sonatype-firewall-icon-solid.svg
  src/main/resources/images/symbols/sonatype-lifecycle-icon-color.svg
  src/main/resources/images/symbols/sonatype-lifecycle-icon-solid.svg
  src/main/resources/images/symbols/sonatype-platform-icon-color.svg
  src/main/resources/images/symbols/sonatype-platform-icon-solid.svg
  src/main/resources/images/symbols/sonatype-repository-icon-color.svg
  src/main/resources/images/symbols/sonatype-repository-icon-solid.svg
Labels: chore

#122 Add Microsoft Edge icon
  src/main/resources/images/symbols/edge-icon-color.svg
  src/main/resources/images/symbols/edge-icon-solid.svg
Labels: enhancement

#123 Add some communication tools
  src/main/resources/images/symbols/discord-icon-color.svg
  src/main/resources/images/symbols/discord-icon-solid.svg
  src/main/resources/images/symbols/msteams-icon-color.svg
  src/main/resources/images/symbols/msteams-icon-solid.svg
  src/main/resources/images/symbols/slack-icon-color.svg
  src/main/resources/images/symbols/slack-icon-solid.svg
Labels: chore

#125 Add pypi
  src/main/resources/images/symbols/pypi-icon-color.svg
  src/main/resources/images/symbols/pypi-icon-solid.svg
Labels: chore

#127 Add quarkus
  src/main/resources/images/symbols/quarkus-icon-color.svg
  src/main/resources/images/symbols/quarkus-icon-solid.svg
Labels: chore

#129 Add .NET core
  src/main/resources/images/symbols/dotnet-core-logo-color.svg
  src/main/resources/images/symbols/dotnet-core-logo-solid.svg
Labels: chore

#128 R icon
  src/main/resources/images/symbols/r-icon-color.svg
  src/main/resources/images/symbols/r-icon-solid.svg
Labels: chore

#131 Add C++
  src/main/resources/images/symbols/cplusplus-icon-color.svg
  src/main/resources/images/symbols/cplusplus-icon-solid.svg
Labels: chore

#132 Add gitpod
  src/main/resources/images/symbols/gitpod-icon-color.svg
  src/main/resources/images/symbols/gitpod-icon-solid.svg
Labels: chore

#134 Add haskell logo
  src/main/resources/images/symbols/haskell-icon-color.svg
  src/main/resources/images/symbols/haskell-icon-solid.svg
Labels: chore

#135 Add fortran icon
  src/main/resources/images/symbols/fortran-icon-color.svg
  src/main/resources/images/symbols/fortran-icon-solid.svg
Labels: chore

#136 Add go wordmark
  src/main/resources/images/symbols/go-wordmark-color.svg
  src/main/resources/images/symbols/go-wordmark-solid.svg
Labels: chore

#137 Add hibernate
  src/main/resources/images/symbols/hibernate-icon-color.svg
  src/main/resources/images/symbols/hibernate-icon-solid.svg
Labels: chore

#138 Add Internet explorer logo
  src/main/resources/images/symbols/internet-explorer-icon-color.svg
  src/main/resources/images/symbols/internet-explorer-icon-solid.svg
Labels: chore

#139 More IDE logos
  src/main/resources/images/symbols/emacs-icon-color.svg
  src/main/resources/images/symbols/emacs-icon-solid.svg
  src/main/resources/images/symbols/goland-icon-color.svg
  src/main/resources/images/symbols/goland-icon-solid.svg
  src/main/resources/images/symbols/neovim-icon-color.svg
  src/main/resources/images/symbols/neovim-icon-solid.svg
  src/main/resources/images/symbols/qodana-icon-color.svg
  src/main/resources/images/symbols/qodana-icon-solid.svg
  src/main/resources/images/symbols/rider-icon-color.svg
  src/main/resources/images/symbols/rider-icon-solid.svg
  src/main/resources/images/symbols/rstudio-icon-color.svg
  src/main/resources/images/symbols/rstudio-icon-solid.svg
  src/main/resources/images/symbols/rubymine-icon-color.svg
  src/main/resources/images/symbols/rubymine-icon-solid.svg
  src/main/resources/images/symbols/webstorm-icon-color.svg
  src/main/resources/images/symbols/webstorm-icon-solid.svg
Labels: chore

#141 Add puppet logo
  src/main/resources/images/symbols/puppet-icon-color.svg
  src/main/resources/images/symbols/puppet-icon-solid.svg
Labels: chore

#143 Add more database logo
  src/main/resources/images/symbols/azuresqldatabase-icon-color.svg
  src/main/resources/images/symbols/azuresqldatabase-icon-solid.svg
  src/main/resources/images/symbols/cassandra-icon-color.svg
  src/main/resources/images/symbols/cassandra-icon-solid.svg
  src/main/resources/images/symbols/cosmosdb-icon-color.svg
  src/main/resources/images/symbols/cosmosdb-icon-solid.svg
  src/main/resources/images/symbols/couchbase-icon-color.svg
  src/main/resources/images/symbols/couchbase-icon-solid.svg
  src/main/resources/images/symbols/couchdb-icon-color.svg
  src/main/resources/images/symbols/couchdb-icon-solid.svg
  src/main/resources/images/symbols/dynamodb-icon-color.svg
  src/main/resources/images/symbols/dynamodb-icon-solid.svg
  src/main/resources/images/symbols/faunadb-icon-color.svg
  src/main/resources/images/symbols/faunadb-icon-solid.svg
  src/main/resources/images/symbols/influxdb-icon-color.svg
  src/main/resources/images/symbols/influxdb-icon-solid.svg
  src/main/resources/images/symbols/rocksdb-icon-color.svg
  src/main/resources/images/symbols/rocksdb-icon-solid.svg
  src/main/resources/images/symbols/sqlite-icon-color.svg
  src/main/resources/images/symbols/sqlite-icon-solid.svg
  src/main/resources/images/symbols/yugabytedb-icon-color.svg
  src/main/resources/images/symbols/yugabytedb-icon-solid.svg
Labels: chore

#142 Add Azure DevOps logo
  src/main/resources/images/symbols/azuredevops-icon-color.svg
  src/main/resources/images/symbols/azuredevops-icon-solid.svg
Labels: chore

#146 Add more hypervisors
  src/main/resources/images/symbols/digitalocean-icon-color.svg
  src/main/resources/images/symbols/digitalocean-icon-solid.svg
  src/main/resources/images/symbols/exoscale-icon-color.svg
  src/main/resources/images/symbols/exoscale-icon-solid.svg
  src/main/resources/images/symbols/heroku-icon-color.svg
  src/main/resources/images/symbols/heroku-icon-solid.svg
  src/main/resources/images/symbols/ovhcloud-icon-color.svg
  src/main/resources/images/symbols/ovhcloud-icon-solid.svg
Labels: chore

#147 Add adobe cs logos
  src/main/resources/images/symbols/illustrator-icon-color.svg
  src/main/resources/images/symbols/illustrator-icon-solid.svg
  src/main/resources/images/symbols/photoshop-icon-color.svg
  src/main/resources/images/symbols/photoshop-icon-solid.svg
  src/main/resources/images/symbols/premierepro-icon-color.svg
  src/main/resources/images/symbols/premierepro-icon-solid.svg
Labels: chore

#145 Fix some icon name
  src/main/resources/images/symbols/gradle-icon-color.svg
  src/main/resources/images/symbols/qodana-icon-color.svg
  src/main/resources/images/symbols/qodana-icon-solid.svg
Labels: bug
