Repository jenkinsci/oss-symbols-api-plugin, pull requests merged in 2025-01, with the labels that each got.

#165 Add logo for sharepoint and rss
  README.md
  src/main/resources/images/symbols/rss-icon-color.svg
  src/main/resources/images/symbols/rss-icon-solid.svg
  src/main/resources/images/symbols/sharepoint-icon-color.svg
  src/main/resources/images/symbols/sharepoint-icon-solid.svg
Labels: chore

#166 feat(java): Require Jenkins core 2.479.1 and Java 17.
  pom.xml
Labels: dependencies

#167 Add svgoconfig
  svgo.config.js
Labels: internal

#168 Add oauth logo
  src/main/resources/images/symbols/oauth-icon-color.svg
  src/main/resources/images/symbols/oauth-icon-solid.svg
Labels: chore
